// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaqIIJ08aIva0Qys52KoLgXNcrjC8LITg',
    appId: '1:534076643636:web:afc965f524296913212d61',
    messagingSenderId: '534076643636',
    projectId: 'myanmar-educational',
    authDomain: 'myanmar-educational.firebaseapp.com',
    storageBucket: 'myanmar-educational.appspot.com',
    measurementId: 'G-M9M70DCL76',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlv18yWmAU_4utKTBuH1eL2bUeLRSXOAM',
    appId: '1:534076643636:android:14ce6ee36793c207212d61',
    messagingSenderId: '534076643636',
    projectId: 'myanmar-educational',
    storageBucket: 'myanmar-educational.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLnqAS8NOvS4zh-3tOfmYiaDhsItf9yzQ',
    appId: '1:534076643636:ios:2b32eb4fd481b398212d61',
    messagingSenderId: '534076643636',
    projectId: 'myanmar-educational',
    storageBucket: 'myanmar-educational.appspot.com',
    iosBundleId: 'com.example.myanmarEducational',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLnqAS8NOvS4zh-3tOfmYiaDhsItf9yzQ',
    appId: '1:534076643636:ios:2d8efcc710323b80212d61',
    messagingSenderId: '534076643636',
    projectId: 'myanmar-educational',
    storageBucket: 'myanmar-educational.appspot.com',
    iosBundleId: 'com.example.myanmarEducational.RunnerTests',
  );
}
